export const plants = [
  {
    id: '1',
    name: 'Pothos',
    category: 'Low Light',
    price: 24.99,
    image: '/pothos-houseplant-in-pot.jpg',
    description: 'Trailing vine perfect for beginners. Thrives in low light conditions.',
  },
  {
    id: '2',
    name: 'Snake Plant',
    category: 'Low Light',
    price: 32.99,
    image: '/snake-plant-sansevieria.png',
    description: 'Hardy and stylish. Requires minimal watering and low light tolerance.',
  },
  {
    id: '3',
    name: 'Peace Lily',
    category: 'Air Purifying',
    price: 28.99,
    image: '/peace-lily-spathiphyllum.jpg',
    description: 'Elegant white flowers. Excellent for purifying indoor air.',
  },
  {
    id: '4',
    name: 'Spider Plant',
    category: 'Air Purifying',
    price: 19.99,
    image: '/spider-plant-green.jpg',
    description: 'Fast-growing and air-purifying. Great for shelves or hanging baskets.',
  },
  {
    id: '5',
    name: 'ZZ Plant',
    category: 'Low Light',
    price: 35.99,
    image: '/zz-plant-zamioculcas.jpg',
    description: 'Glossy leaflets and upright growth. Extremely low maintenance.',
  },
  {
    id: '6',
    name: 'Areca Palm',
    category: 'Air Purifying',
    price: 45.99,
    image: '/areca-palm-tropical-plant.jpg',
    description: 'Tropical beauty with feathery fronds. Natural air purifier.',
  },
]
